//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caso1_AdrianMonge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignaturas
    {
        public int Id { get; set; }
        public string CarreraProfesional { get; set; }
        public string CodigoAsignatura { get; set; }
        public string NombreAsignatura { get; set; }
        public decimal Creditos { get; set; }
        public string CuatrimestreAcademico { get; set; }
        public int HorasSemanales { get; set; }
        public int DuracionSemanas { get; set; }
        public System.DateTime Inicio { get; set; }
        public System.DateTime Termino { get; set; }
        public string Docente { get; set; }
        public string Correo { get; set; }
    }
}
